### ISSUE TITLE
King also demotes to a Pawn 

### ISSUE THREAD

**Issue by dszvivian** [Jiganesh/Pawnhub#1]
How does the GameLoop End?
It's through Checkmate right?

So i guess, We need to check for legal moves before making a move

![image](https://github.com/Jiganesh/Pawnhub/assets/93795205/c3f3dc42-3a1e-4ff8-b32b-da8965596818)

**Comment by Jiganesh** [comment]
FIXED [Commit](https://github.com/Jiganesh/Pawnhub/commit/a9b542f6070e8d172e2aa78d69ab7c02f1759c1a)
